### PR TITLE
Add prototype of benchmarking framework.

### PR DESCRIPTION
**Pull request by paulosjca**
This commit adds containing the prototype of a benchmarking framework that will replace the one currently described here:

https://grpc.io/docs/guides/benchmarking/

This prototype was originally developed in a personal fork of https://github.com/grpc/grpc. The version in this commit separates the benchmarking functionality from the main gRPC repository.

### CODE REVIEW

**Comment by jtattermusch** [comment]
CC @codeblooded

**Comment by paulosjca** [comment]
Development happened in a personal fork of https://github.com/grpc/grpc. The original commits are intermingled with commits for the rest of the repository. The code also needed to be moved and updated, for instance to reflect the changed paths in go packages. Since this is a prototype, it is simpler to add the code in a single commit and start from there. History before this point is preserved on the testctrl branch of the personal fork: https://github.com/codeblooded/grpc.

**Comment by jtattermusch** [comment]
Thanks! Let's make all the development happen here in this repo from now on.

**Comment by paulosjca** [comment]
Just to be clear, we are assuming any development will take place in the yet-to-be-created repository https://github.com/grpc/test-infra, not in https://github/com/jtattermusch/test-infra.

**Comment by jtattermusch** [comment]
@paulosjca as mentioned before, we will not "create" a repository under "grpc/test-infra". We will take this repository and transfer it under "grpc" org so this repository (https://github.com/jtattermusch/test-infra) will BECOME grpc/test-infra (with all its PRs, issues, commits and everything else that belongs to it). This is also the reason why should be developing against this repo for now, until the transfer happens (the act of transferring isn't blocking us in any way).

https://help.github.com/en/github/administering-a-repository/transferring-a-repository#whats-transferred-with-a-repository

**Pull request merged**
